apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    prometheus: prometheus
spec:
  replicas: 2
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector:
    matchExpressions:
    - {}
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists